### ISSUE TITLE
Razer Huntsman Elite Underglow

### ISSUE THREAD

**Issue by kogeki** [Teskann/razer-waver#1]
Hi,

Awesome script. How do I get this script to utilize the underglow on the Huntsman Elite? 

Thanks!

**Comment by Teskann** [comment]
Hi Kogeki ! Thanks, I'm glad you like the script ! 😀

I do not own a Huntsman Elite Keyboard and my keyboard doen't have underglow, so I can not really help you.
First be sure it is supported by Polychromatic.
Underglow leds are probably considered as a row in the matrix when you edit an effect. Try to use the parameter `-r` to set the correct amount of rows for your device. Maybe you should change the device name in the script file (`map_device`), that is hardcoded as `"Razer Ornata V2"`.

Keep me updated if it works ! Good luck 😉

**Comment by kogeki** [comment]
Thanks. Changing the hard coded value to "Razer Huntsman Elite" and using `python create-wave.py -d 1 --fps 60 -r 9` as the command works perfectly.

**Comment by Teskann** [comment]
Great ! I'll update the script to pass the device name as an argument and add more info about the rows/columns in the readme ! 👍
